### ISSUE TITLE
fix links to tutor-notes source code on overhang.io and pypi.org

### ISSUE THREAD

**Issue by Carlos-Muniz** [overhangio/tutor-notes#12]
The links to the source code for the repo tutor-notes [returns 404](https://github.com/overhangio/tutor/tree/master/plugins/notes).

The Source code links need to be changed on the [overhang.io page for tutor-notes](https://overhang.io/tutor/plugin/notes) and the [pypi.org page for tutor-notes](https://pypi.org/project/tutor-notes/).

**Comment by NeOneSoft** [comment]
Nice catch!!
