### ISSUE TITLE
tutor-notes codebase Python 3.12 upgrade

### ISSUE THREAD

**Issue by DawoudSheraz** [overhangio/tutor-notes#33]
- [x] Ensure tutor-notes codebase is compatible with Python 3.12
- [x] Update Python to 3.12 in Dockerfile for nightly and ensure the image builds as expected. The changes would be merged to nightly. This task would rely on upgrade of edx-notes-api to Python 3.12  

See https://github.com/overhangio/tutor/issues/1004 for the context.

**Comment by DawoudSheraz** [comment]
FYI @jfavellar90

**Comment by DawoudSheraz** [comment]
@jfavellar90 FYI -- Reminder

**Comment by jfavellar90** [comment]
@DawoudSheraz Hi, This is to report that this update is in progress. Tomorrow I expect to share a functional PR with the building of the notes image with Python 3.12. Apparently, the Tutor image building in Python 3.11 is still [blocked](https://github.com/overhangio/tutor/issues/1006) so I'll build the openedx image with the Dockerfile from the nightly Tutor branch.

**Comment by jfavellar90** [comment]
Since https://github.com/overhangio/tutor-notes/pull/36 was merged, I proceed to close this issue
